### ISSUE TITLE
`QString::null` is deprecated

### ISSUE THREAD

**Issue by ElroyJ** [openivef/ivef-sdk#93]
The generated C++ code relies heavily on `QString::null` for empty strings. When compiling, QMake/gcc gives deprecation warnings for `QString::null`. According to the documentation `QString()` should be used instead of `QString::null`.

Replacing all instances of `QString::null` by `QString()` in `codegenqt.cpp` seems to solve the problem.

**Comment by ajheres** [comment]
Thanks for your input. Right issue, can be followed up.

**Comment by ajheres** [comment]
Issue is part of release [openivef/ivef-sdk/releases/tag/IVEF_1_1_0](url)
